### ISSUE TITLE
Code is questionable

### ISSUE THREAD

**Issue by AquaMinerale2b2t** [xyzbtw/StashMoverPlugin#1]
make it better and remove the rat xoxo

**Comment by xyzbtw** [comment]
i no no wanna, u do it pls

**Comment by xyzbtw** [comment]
mineral u on some ugu gaga shit

**Comment by AquaMinerale2b2t** [comment]
that's not the case

**Comment by xyzbtw** [comment]
clearly it is

**Comment by AquaMinerale2b2t** [comment]
there isnt a single bit of the aforementioned "ugu gaga" shit about me

**Comment by xyzbtw** [comment]
whatever you say ugu gaga man

**Comment by xyzbtw** [comment]
MONKEY
